site_name: Linarc

theme : 
  name: cinder


nav:
- Home: 'index.md'
- User Guide:
    - 'Dashboard': 'writing-your-docs.md'
    - 'Conversations': 'styling-your-docs.md'

- About:
    - 'License': 'license.md'
    - 'Release Notes': 'release-notes.md'
